{% set name = "cleopatra" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/cleopatra/archive/{{ version }}.tar.gz
  sha256: 890a1f89cc3af1d51301ae067ed29627f9255659fc9879b4ba0c1df0f9abe5f3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python  >=3.11
    - pip >=23.2.1
  run:
    - python  >=3.11
    - pip >=23.2.1
    - numpy =1.25.2
    - matplotlib >=3.7.2
    - hpc >=0.1.2
    - ffmpeg-python

test:
  imports:
    - cleopatra

about:
  home: https://github.com/MAfarrag/cleopatra
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: matplotlib utility package
  description: |
    matplotlib utility package.
  dev_url: https://github.com/MAfarrag/cleopatra
  doc_url: https://cleopatra.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/cleopatra/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
