{% set name = "cleopatra" %}
{% set version = "0.2.3.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/cleopatra/archive/{{ version }}.tar.gz
  sha256: a313a4380eea99acc30f15ffc92edf0fb84912f26b5e8bf314448fbca314cdc0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python  >=3.9,<3.12
    - pip >=22.2.2
    - poetry >=1.1.15
  run:
    - python  >=3.9,<3.12
    - pip >=22.2.2
    - numpy >=1.23.0
    - matplotlib >=3.5.3

test:
  imports:
    - cleopatra

about:
  home: https://github.com/MAfarrag/cleopatra
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: matplotlib utility package
  description: |
    matplotlib utility package.
  dev_url: https://github.com/MAfarrag/cleopatra
  doc_url: https://cleopatra.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/cleopatra/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
