{% set python_min = "3.12" %}
{% set name = "cleopatra" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/cleopatra/archive/{{ version }}.tar.gz
  sha256: 85467f84a3f501a44cc67fdacd7ced2797dd3e28edd7fab93b6f57a4bd8421cd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip >=24.0.0
  run:
    - python >={{ python_min }}
    - numpy >=2.0.0
    - hpc >=0.1.4
    - pip >=24.0.0
    - matplotlib >=3.8.4
    - ffmpeg-python

test:
  requires:
    - python {{ python_min }}
  imports:
    - cleopatra

about:
  home: https://github.com/MAfarrag/cleopatra
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: matplotlib utility package
  description: |
    matplotlib utility package.
  dev_url: https://github.com/MAfarrag/cleopatra
  doc_url: https://cleopatra.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/cleopatra/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
