{% set name = "cleopatra" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/cleopatra/archive/{{ version }}.tar.gz
  sha256: 506bb1f8c3e4485b767faf1bbb6fc0163ea80faa8d4e7bb904de12381eecba2d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python  >=3.12
    - pip >=24.0.0
  run:
    - python  >=3.12
    - numpy >=2.0.0
    - hpc >=0.1.4
    - pip >=24.0.0
    - matplotlib >=3.8.4
    - ffmpeg-python

test:
  imports:
    - cleopatra

about:
  home: https://github.com/MAfarrag/cleopatra
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: matplotlib utility package
  description: |
    matplotlib utility package.
  dev_url: https://github.com/MAfarrag/cleopatra
  doc_url: https://cleopatra.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/cleopatra/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
