{% set name = "cleopatra" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/cleopatra/archive/{{ version }}.tar.gz
  sha256: a64e877dcdd071d204b9a31a5a4d4b754463520b97e32d867b5c9f93b0bfbcfc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python  >=3.9,<3.11
    - pip >=22.3.1
  run:
    - python  >=3.9,<3.11
    - pip >=22.3.1
    - numpy =1.24.1
    - matplotlib >=3.6.2
    - hpc >=0.1.1
    - ffmpeg-python

test:
  imports:
    - cleopatra

about:
  home: https://github.com/MAfarrag/cleopatra
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: matplotlib utility package
  description: |
    matplotlib utility package.
  dev_url: https://github.com/MAfarrag/cleopatra
  doc_url: https://cleopatra.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/cleopatra/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
