{% set name = "cleopatra" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/cleopatra/archive/{{ version }}.tar.gz
  sha256: B17CD7AA19EE12A9337575A9B25772E3BA88F77165A98E3FD52DBD73987B3DE6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python  >=3.9,<3.11
    - pip >=22.3.1
    - poetry >=1.2.2
  run:
    - python  >=3.9,<3.11
    - pip >=22.3.1
    - numpy =1.23.5
    - matplotlib >=3.6.2
    - serapeum_utils >=0.1.1

test:
  imports:
    - cleopatra

about:
  home: https://github.com/MAfarrag/cleopatra
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: matplotlib utility package
  description: |
    matplotlib utility package.
  dev_url: https://github.com/MAfarrag/cleopatra
  doc_url: https://cleopatra.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/cleopatra/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
